[run]
init_cmds = [["./gogs", "web"]]
watch_all = true
watch_dirs = [
	"$WORKDIR/conf/locale",
	"$WORKDIR/cmd",
	"$WORKDIR/models",
	"$WORKDIR/modules",
	"$WORKDIR/routers"
]
watch_exts = [".go", ".ini"]
build_delay = 1500
cmds = [
	["go", "install", "-tags", "sqlite"],
	["go", "build", "-tags", "sqlite"],
	["./gogs", "web"]
]