filesets:
    includes:
        - conf
        - etc
        - public
        - scripts
        - templates
        - LICENSE
        - README.md
        - README_ZH.md
    excludes:
        - \.git
settings:
        build: |
            if test "$GOOS" = "windows" -a "$GOARCH" = "386"
            then
                go install -v
            else
                go get -v -tags "sqlite redis memcache cert" github.com/gogits/gogs
                go install -v -tags "sqlite redis memcache cert"
            fi
