filesets:
    includes:
        - conf
        - etc
        - public
        - scripts
        - templates
        - LICENSE
        - README.md
        - README_ZH.md
        - start.bat
    excludes:
        - \.git
settings:
        build: |
            go get -u -tags "sqlite redis memecache" github.com/gogits/gogs
            go install -tags "sqlite redis memecache"
