targets:
  ubuntu-14.04:
    build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
      - git
  ubuntu-12.04:
    build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
      - git
  debian-7:
    build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
      - git
  centos-6:
    build_dependencies:
      - pam-devel
    dependencies:
      - pam
      - git
before:
  - mv packager/Procfile .
  - mv packager/.godir .
after:
  - mv bin/main gogs
after_install: ./packager/debian/postinst
