targets:
  ubuntu-14.04:
  ubuntu-12.04:
  debian-7:
  centos6:
build_dependencies:
  - mercurial
  - bzr
dependencies:
  - git
before:
  - mv packager/Procfile .
  - mv packager/.godir .
after:
  - mv bin/main gogs
after_install: ./packager/debian/postinst
