language: go

go:
  - 1.6
  - 1.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev
  - go get github.com/msteinert/pam

install:
  - go get -t -v ./...

script: |
  go build -v -tags "pam"

  for pkg in $(go list ./... | grep -v /vendor/)
  do
    go test -v -race -cover -coverprofile $GOPATH/src/$pkg/coverage.out $pkg || exit 1
  done

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
    urls:
      - https://webhooks.gitter.im/e/ee6b822f3cf54c98e70c
      - https://webhooks.gitter.im/e/87428658ef177ce8a7e4
      - https://webhooks.gitter.im/e/a1d2b69804dfda72187e
