language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev

script: go build -v -tags "pam"

notifications:
  email:
    - u@gogs.io
  slack: gophercn:o5pSanyTeNhnfYc3QnG0X7Wx
