version: 0.2

phases:
  build:
    commands:
       - go get && go build -o bin/application 
#        - zip -r artifact.zip Buildfile Procfile build.sh bin/
artifacts:
  files:
#    - Buildfile
    - Procfile
#    - build.sh
    - bin/*
